name: Stealth Ping Render & Alert

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

env:
  RENDER_URL: ${{ secrets.RENDER_URL }}

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Ping /health with browser user-agent
        id: ping
        run: |
          START=$(date +%s%3N)
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/122.0.0.0 Safari/537.36" \
            "$RENDER_URL/health")
          END=$(date +%s%3N)
          DURATION=$((END - START))

          echo "HTTP status: $HTTP_STATUS"
          echo "Response time: ${DURATION}ms"

          echo "http_status=$HTTP_STATUS" >> $GITHUB_OUTPUT
          echo "duration=$DURATION" >> $GITHUB_OUTPUT

      - name: Alert if site is DOWN (non-200)
        if: steps.ping.outputs.http_status != '200'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RENDER_URL: ${{ secrets.RENDER_URL }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="❌ *Render site appears DOWN!*%0AStatus code: ${{ steps.ping.outputs.http_status }}%0AURL: $RENDER_URL" \
            -d parse_mode=Markdown

      - name: Alert if site is SLOW (likely asleep)
        if: steps.ping.outputs.http_status == '200' && steps.ping.outputs.duration > 10000
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RENDER_URL: ${{ secrets.RENDER_URL }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="⚠️ *Render site is slow (possibly asleep)*%0AResponse time: ${{ steps.ping.outputs.duration }}ms%0AURL: $RENDER_URL" \
            -d parse_mode=Markdown
